# Pytorch: Machine Learning library

[Pytorch](https://pytorch.org/) is one of open-source, modern deep learning libraries out there and what we will use in this workshop. Other popular libraries include [Tensorflow](https://www.tensorflow.org/), [Keras](https://keras.io), [MXNet](https://mxnet.apache.org), [Spark ML](https://spark.apache.org/mllib/), etc. ...

All of those libraries works very similar in terms of implementing your neural network architecture. If you are new, probably any of Pytorch/Keras/Tensorflow would work well with lots of guidance/examples/discussion-forums online! Common things you have to learn include:

1. [Data types](#datatype) (typically arbitrary dimension matrix, or _tensor_ )
2. [Data loading tools](#dataloader) (streamline prepping data into appropraite types from input files)
3. [Chaining operations](#graph) = a _computation graph_ 

In this notebook, we cover the basics part in each of topics above.

<a href="datatype"></a>
## 1. Tensor data types in PyTorch
In `pytorch`, we use `torch.Tensor` object to represent data matrix. It is a lot like `numpy` array but not quite the same. `torch` provide APIs to easily convert data between `numpy` array and `torch.Tensor`. Let's play a little bit.

In [1]:
from __future__ import print_function
import numpy as np
import torch
SEED=123
np.random.seed(SEED)
torch.manual_seed(SEED)

... yep, that's how we set pytorch random number seed! (see Python-03-Numpy if you don't know about a seed)

### Creating a torch.Tensor

Pytorch provides constructors similar to numpy (and named same way where possible to avoid users having to look-up function names). Here are some examples.

In [2]:
# Tensor of 0s = numpy.zeros
t=torch.zeros(2,3)
print('torch.zeros:\n',t)

# Tensor of 1s = numpy.ones
t=torch.ones(2,3)
print('\ntorch.ones:\n',t)

# Tensor from a sequential integers = numpy.arange
t=torch.arange(0,6,1).reshape(2,3).float()
print('\ntorch.arange:\n',t)

# Normal distribution centered at 0.0 and sigma=1.0 = numpy.rand.randn
t=torch.randn(2,3)
print('\ntorch.randn:\n',t)

torch.zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

torch.ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

torch.arange:
 tensor([[0., 1., 2.],
        [3., 4., 5.]])

torch.randn:
 tensor([[-0.1115,  0.1204, -0.3696],
        [-0.2404, -1.1969,  0.2093]])


... or you can create from a simple list, tuple, and numpy arrays.

In [3]:
# Create numpy array
data_np = np.zeros([10,10],dtype=np.float32)
# Fill something
np.fill_diagonal(data_np,1.)
print('Numpy data\n',data_np)

# Create torch.Tensor
data_torch = torch.Tensor(data_np)
print('\ntorch.Tensor data\n',data_torch)

# One can make also from a list
data_list = [1,2,3]
data_list_torch = torch.Tensor(data_list)
print('\nPython list :',data_list)
print('torch.Tensor:',data_list_torch)

Numpy data
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

torch.Tensor data
 tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Python list : [1, 2, 3]
torch.Tensor: tensor([1., 2., 3.])


Converting back from `torch.Tensor` to a numpy array can be easily done

In [4]:
# Bringing back into numpy array
data_np = data_torch.numpy()
print('\nNumpy data (converted back from torch.Tensor)\n',data_np)


Numpy data (converted back from torch.Tensor)
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Ordinary operations to an array also exists like `numpy`.

In [5]:
# mean & std
print('mean',data_torch.mean(),'std',data_torch.std(),'sum',data_torch.sum())

mean tensor(0.1000) std tensor(0.3015) sum tensor(10.)


We see the return of those functions (`mean`,`std`,`sum`) are tensor objects. If you would like a single scalar value, you can call `item` function.

In [6]:
# mean & std
print('mean',data_torch.mean().item(),'std',data_torch.std().item(),'sum',data_torch.sum().item())

mean 0.10000000149011612 std 0.30151134729385376 sum 10.0


### Tensor addition and multiplication
Common operations include element-wise multiplication, matrix multiplication, and reshaping. Read the [documentation](https://pytorch.org/docs/stable/tensors.html) to find the right function for what you want to do!

In [7]:
# Two matrices 
data_a = np.zeros([3,3],dtype=np.float32)
data_b = np.zeros([3,3],dtype=np.float32)
np.fill_diagonal(data_a,1.)
data_b[0,:]=1.
# print them
print('Two numpy matrices')
print(data_a)
print(data_b,'\n')

# Make torch.Tensor
torch_a = torch.Tensor(data_a)
torch_b = torch.Tensor(data_b)

print('torch.Tensor element-wise multiplication:')
print(torch_a*torch_b)

print('\ntorch.Tensor matrix multiplication:')
print(torch_a.matmul(torch_b))

print('\ntorch.Tensor matrix addition:')
print(torch_a-torch_b)

print('\nadding a scalar 1:')
print(torch_a+1)

Two numpy matrices
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]] 

torch.Tensor element-wise multiplication:
tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

torch.Tensor matrix multiplication:
tensor([[1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

torch.Tensor matrix addition:
tensor([[ 0., -1., -1.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

adding a scalar 1:
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])


### Reshaping

You can access the tensor shape via `.shape` attribute like numpy

In [8]:
print('torch_a shape:',torch_a.shape)
print('The 0th dimension size:',torch_a.shape[0])

torch_a shape: torch.Size([3, 3])
The 0th dimension size: 3


Similarly, there is a `reshape` function

In [9]:
torch_a.reshape(1,9).shape

torch.Size([1, 9])

... and you can also use -1 in the same way you used for numpy

In [10]:
torch_a.reshape(-1,3).shape

torch.Size([3, 3])

### Indexing (Slicing)

We can use a similar indexing trick like we tried with a numpy array

In [11]:
torch_a[0,:]

tensor([1., 0., 0.])

or a boolean mask generation

In [12]:
mask = torch_a == 0.
mask

tensor([[False,  True,  True],
        [ True, False,  True],
        [ True,  True, False]])

... and slicing with it using `masked_select` function

In [13]:
torch_a.masked_select(~mask)

tensor([1., 1., 1.])

<a href="dataloader"></a>
## 2. Data loading tools in Pytorch

In Python-02-Python, we covered an iteratable class and how it could be useful to generalize a design of data access tools. Pytorch (and any other ML libraries out there) provides a generalized tool to interface such iteratable data instance called `DataLoader`. Desired capabilities of such tools include ability to choose random vs. ordered subset in data, parallelized workers to simultaneously prepare multiple batch data, etc..

Let's practice the use of `DataLoader`. 

First, we define the same iteretable class mentioned in Python-02-Python notebook.

In [14]:
class dataset:
    
    def __init__(self):
        self._data = tuple(range(100))
        
    def __len__(self):
        return len(self._data)
    
    def __getitem__(self,index):
        return self._data[index]
    
data = dataset()

Here is how you can instantiate a `DataLoader`. We construct an instance called `loader` that can automatically packs 10 elements of data (`batch_size=10`) that is randomly selected (`shuffle=True`) using 1 parallel worker to prepare such data (`num_workers=1`).

In [15]:
from torch.utils.data import DataLoader
loader = DataLoader(data,batch_size=10,shuffle=True,num_workers=1)

The dataloader itself is an iterable object. We created a dataloader with batch size 10 where the dataset instance has the length 100. This means, if we iterate on the dataloader instance, we get 10 separate batch data.

In [16]:
for index, batch_data in enumerate(loader):
    print('Batch entry',index,'... batch data',batch_data)

Batch entry 0 ... batch data tensor([14,  7, 53, 63, 50, 96, 39, 64, 19,  8])
Batch entry 1 ... batch data tensor([31,  3, 52, 22, 78, 20,  9, 49, 72, 38])
Batch entry 2 ... batch data tensor([91, 13, 92, 48, 80, 76, 32,  1, 45, 33])
Batch entry 3 ... batch data tensor([18, 30, 10, 37, 77, 23, 90,  2, 47, 54])
Batch entry 4 ... batch data tensor([93,  5, 88, 59, 94, 36, 25, 98,  4, 27])
Batch entry 5 ... batch data tensor([ 6, 46, 81, 89, 58, 84, 67, 74, 43, 71])
Batch entry 6 ... batch data tensor([57, 97, 24, 73, 15, 16, 28, 41, 82, 60])
Batch entry 7 ... batch data tensor([21, 62, 83, 61, 11, 65, 87, 95, 69, 12])
Batch entry 8 ... batch data tensor([29, 35, 68, 79, 85, 40, 75, 44,  0, 55])
Batch entry 9 ... batch data tensor([66, 34, 26, 17, 86, 56, 42, 70, 99, 51])


We can see that data elements are chosen randomly as we chose "shuffle=True". Does this cover all data elements in the dataset? Let's check this by combining all iterated data.

In [17]:
data_collection = []
for index,batch_data in enumerate(loader):
    data_collection += [int(v) for v in batch_data]
    
import numpy as np
np.unique(data_collection)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

This covers the minimal concept of `DataLoader` you need to know in order to follow the workshop. You can read more about `DataLoader` in pytorch documentation [here](https://pytorch.org/docs/stable/data.html) and also more extended example in [their tutorial](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html) if you are interested in exploring yourself.

<a href="graph"></a>
## 3. Computation graph

The last point to cover is how to chain modularized mathematical operations. 

To get started, let's introduce a few, well used mathematical operations in pytorch.

* `torch.nn.ReLU` ([link](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html#torch.nn.ReLU)) ... a function that takes an input tenor and outputs a tensor of the same shape where elements are 0 if the corresponding input element has a value below 0, and otherwise the same value.
* `torch.nn.Softmax` ([link](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html#torch.nn.Softmax)) ... a function that applies a [softmax function](https://en.wikipedia.org/wiki/Softmax_function) on the specified dimension of an input data.
* `torch.nn.MaxPool2d` ([link](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html#torch.nn.MaxPool2d)) ... a function that down-sample the input matrix by taking maximum value from sub-matrices of a specified shape.

Let's see what each of these functions do first using a simple 2D matrix data.

In [18]:
# Create a 2D tensor of shape (1,5,5) with some negative and positive values
data = torch.randn(25).reshape(1,5,5)
data

tensor([[[-0.0215,  1.0731, -0.1408, -0.5394, -1.2782],
         [-0.8107,  1.3818, -0.0694,  1.2088, -0.0086],
         [ 1.8576,  2.1321, -0.5056, -0.7988, -1.8127],
         [ 1.1846,  1.7602,  1.2117, -0.8632,  1.3337],
         [ 0.0771, -0.0522, -1.0565,  1.1510, -0.4669]]])

Here's how `ReLU` works

In [19]:
op0 = torch.nn.ReLU()
op0(data)

tensor([[[0.0000, 1.0731, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.3818, 0.0000, 1.2088, 0.0000],
         [1.8576, 2.1321, 0.0000, 0.0000, 0.0000],
         [1.1846, 1.7602, 1.2117, 0.0000, 1.3337],
         [0.0771, 0.0000, 0.0000, 1.1510, 0.0000]]])

Here's how `Softmax` works

In [20]:
op1 = torch.nn.Softmax(dim=2)
op1(data)

tensor([[[0.1737, 0.5191, 0.1542, 0.1035, 0.0494],
         [0.0458, 0.4105, 0.0962, 0.3453, 0.1022],
         [0.3991, 0.5251, 0.0376, 0.0280, 0.0102],
         [0.1963, 0.3490, 0.2016, 0.0253, 0.2278],
         [0.1752, 0.1540, 0.0564, 0.5128, 0.1017]]])

Here's how `MaxPool2d` works with a kernel shape (5,1)

In [21]:
op2 = torch.nn.MaxPool2d(kernel_size=(1,5))
op2(data)

tensor([[[1.0731],
         [1.3818],
         [2.1321],
         [1.7602],
         [1.1510]]])

So if we want to define a computation graph that applies these operations in a sequential order, we could try:

In [22]:
op2(op1(op0(data)))

tensor([[[0.4223],
         [0.3854],
         [0.4726],
         [0.3373],
         [0.4366]]])

Pytorch provides tools called _containers_ to make this easy. Let's try `torch.nn.Sequential` (see different type of containers [here](https://pytorch.org/docs/stable/nn.html#containers)).

In [23]:
myop = torch.nn.Sequential(op0,op1,op2)
myop(data)

tensor([[[0.4223],
         [0.3854],
         [0.4726],
         [0.3373],
         [0.4366]]])

We might wonder "Can I add a custom operation to this graph?" Yes, we can add any _module_ that inherits from `torch.nn.Module` class. Let's define one for ourself.

In [24]:
class AddOne(torch.nn.Module):

    # always call the base class constructor for defining your torch.nn.Module inherit class!
    def __init__(self):
        super().__init__()
        
    # forward needs to be defined. This is called by "()" function call.
    def forward(self,input):
        
        return input + 1;

Now let's add our operation

In [25]:
myop = torch.nn.Sequential(op0,op1,op2,AddOne())
myop(data)

tensor([[[1.4223],
         [1.3854],
         [1.4726],
         [1.3373],
         [1.4366]]])

Of course, you can also embed `op0`, `op1`, and `op2` inside one module.

In [26]:
class MyOp(torch.nn.Module):
    
    def __init__(self):
        super().__init__()
        self._sequence = torch.nn.Sequential(torch.nn.ReLU(), 
                                             torch.nn.Softmax(dim=2), 
                                             torch.nn.MaxPool2d(kernel_size=(1,5)),
                                             AddOne(),
                                            )
        
    def forward(self,input):
        
        return self._sequence(input)

Let's try using it.

In [27]:
myop = MyOp()
myop(data)

tensor([[[1.4223],
         [1.3854],
         [1.4726],
         [1.3373],
         [1.4366]]])

## Extra: GPU acceleration

**This section only works if you run this notebook on a GPU-enabled machine (not on the binder unfortunately)**

Putting `torch.Tensor` on GPU is as easy as calling `.cuda()` function (and if you want to bring it back to cpu, call `.cpu()` on a `cuda.Tensor`). Let's do a simple speed comparison. 

Create two arrays with an identical data type, shape, and values.

In [28]:
# Create 1000x1000 matrix
data_np=np.zeros([1000,1000],dtype=np.float32)
data_cpu = torch.Tensor(data_np).cpu()
#data_gpu = torch.Tensor(data_np).cuda()

Time fifth power of the matrix on CPU

In [29]:
%%timeit
mean = (data_cpu ** 5).mean().item()

2.48 ms ± 324 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


... and next on GPU

In [30]:
%%timeit
mean = (data_gpu ** 5).mean().item()

NameError: name 'data_gpu' is not defined

... which is more than x10 faster than the cpu counter part :)

But there's a catch you should be aware! Preparing a data on GPU does take time because data needs to be sent to GPU, which could take some time. Let's compare the time it takes to create a tensor on CPU v.s. GPU.

In [31]:
%%timeit
data_np=np.zeros([1000,1000],dtype=np.float32)
data_cpu = torch.Tensor(data_np).cpu()

212 µs ± 14.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
%%timeit
#data_np=np.zeros([1000,1000],dtype=np.float32)
#data_gpu = torch.Tensor(data_np).cuda()

ValueError: empty body on For

As you can see, it takes nearly 10 times longer time to create this particular data tensor on our GPU. This speed depends on many factors including your hardware configuration (e.g. CPU-GPU communication via PCI-e or NVLINK). It makes sense to move computation that takes longer than this data transfer time to perform on GPU.